const SUBJECTS = {
  paleontology:  'Paleontology',
  antiquity: 'Antiquity'
};

const RATINGS = { 4: 'Loved', 3: 'Liked', 2: 'Ok', 1: 'Didn\'t like' };
const KINDS = { book: 'Book', film: 'Film', music: 'Music', podcast: 'Podcast', play: 'Play' };

const ITEMS = [
  {
    id: 'prehistoricplanet',
    title: 'Prehistoric Planet',
    creator: 'Jon Favreau',
    year: 2022,
    kind: 'film',
    status: 'inprogress',
    rating: null,
    subject: 'paleontology',
    genre: 'Documentary',
    also: ['deeptime'],
    note: 'Many things are not based on strict facts but help imagine how life was really then.'
    },
  {
    id: 'iliad',
    title: 'Iliad',
    creator: 'Homer',
    year: -700,
    kind: 'book',
    status: 'finished',
    rating: 3,
    subject: 'antiquity',
    genre: 'Poem',
    also: ['greece'],
    note: 'Lots of repeating (it\'s made to be told, not be written), the theory about several authors seems to be correct.'
    },
  {
    id: 'odyssey',
    title: 'Odyssey',
    creator: 'Homer',
    year: -750,
    kind: 'book',
    status: 'finished',
    rating: 2,
    subject: 'antiquity',
    genre: 'Poem',
    also: ['greece'],
    note: 'Many "adventures" that can be hard to imagine.'
    },
  {
    id: 'odyssey2026',
    title: 'Odyssey',
    creator: 'Nolan',
    year: 2026,
    kind: 'film',
    status: 'finished',
    rating: 4,
    subject: 'antiquity',
    genre: 'Action',
    also: ['greece'],
    note: 'Story about returning from it.'
    },
  {
    id: 'worksanddays',
    title: 'Works and days',
    creator: 'Hesiod',
    year: -700,
    kind: 'book',
    status: 'finished',
    rating: 1,
    subject: 'antiquity',
    genre: 'Poem',
    also: ['greece'],
    note: 'Lots of advices that are not practical today.'
    },
  {
    id: 'theogony',
    title: 'Theogony',
    creator: 'Hesiod',
    year: -700,
    kind: 'book',
    status: 'finished',
    rating: 1,
    subject: 'antiquity',
    genre: 'Poem',
    also: ['greece'],
    note: 'Once again Greek myths.'
    },
  {
    id: 'aethiopica',
    title: 'Aethiopica',
    creator: 'Heliodorus of Emesa',
    year: -370,
    kind: 'book',
    status: 'finished',
    rating: 3,
    subject: 'antiquity',
    genre: 'Novel',
    also: ['greece'],
    note: 'Dramatic story about very beautiful people who are very kind, and very noble, and very lucky.'
    },
  {
    id: 'oresteia',
    title: 'The Oresteia',
    creator: 'Aeschylus',
    year: -550,
    kind: 'play',
    status: 'finished',
    rating: 4,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: 'Grand tragedy.'
    },
  {
    id: 'prometheusbound',
    title: 'Prometheus Bound',
    creator: 'Aeschylus',
    year: -424,
    kind: 'play',
    status: 'finished',
    rating: 2,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: 'Too pretentious.'
    },
  {
    id: 'oedipusrex',
    title: 'Oedipus Rex',
    creator: 'Sophocles',
    year: -429,
    kind: 'play',
    status: 'finished',
    rating: 3,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: 'Very dramatic and intense.'
    },
  {
    id: 'antigone',
    title: 'Antigone',
    creator: 'Sophocles',
    year: -441,
    kind: 'play',
    status: 'notstarted',
    rating: null,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: ''
    },
  {
    id: 'electrasophocles',
    title: 'Electra',
    creator: 'Sophocles',
    year: -420,
    kind: 'play',
    status: 'notstarted',
    rating: null,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: ''
    },
  {
    id: 'bacchae',
    title: 'The Bacchae',
    creator: 'Euripides',
    year: -405,
    kind: 'play',
    status: 'finished',
    rating: 4,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: 'Madness is so intense.'
    },
  {
    id: 'medea',
    title: 'Medea',
    creator: 'Euripides',
    year: -431,
    kind: 'play',
    status: 'finished',
    rating: 2,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: ''
    },
  {
    id: 'alcestis',
    title: 'Alcestis',
    creator: 'Euripides',
    year: -438,
    kind: 'play',
    status: 'finished',
    rating: 1,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: ''
    },
  {
    id: 'hippolytus',
    title: 'Hippolytus',
    creator: 'Euripides',
    year: -428,
    kind: 'play',
    status: 'notstarted',
    rating: null,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: ''
    },
  {
    id: 'electraeuripides',
    title: 'Electra',
    creator: 'Euripides',
    year: -413,
    kind: 'play',
    status: 'notstarted',
    rating: null,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: ''
    },
  {
    id: 'lysistrata',
    title: 'Lysistrata',
    creator: 'Aristophanes',
    year: -411,
    kind: 'play',
    status: 'finished',
    rating: 2,
    subject: 'antiquity',
    genre: 'Comedy',
    also: ['greece'],
    note: 'Humour comes from women\'s powerless position in society.'
    },
  {
    id: 'frogs',
    title: 'The Frogs',
    creator: 'Aristophanes',
    year: -405,
    kind: 'play',
    status: 'finished',
    rating: 1,
    subject: 'antiquity',
    genre: 'Comedy',
    also: ['greece'],
    note: 'Comedy about who\'s better poet, pretty niche.'
    },
  {
    id: 'clouds',
    title: 'The Clouds',
    creator: 'Aristophanes',
    year: -423,
    kind: 'play',
    status: 'finished',
    rating: 1,
    subject: 'antiquity',
    genre: 'Comedy',
    also: ['greece'],
    note: 'Comedy about philosophers, very niche.'
    },
  {
    id: 'symposium',
    title: 'The Symposium',
    creator: 'Plato',
    year: -375,
    kind: 'book',
    status: 'finished',
    rating: 4,
    subject: 'antiquity',
    genre: 'Dialogue',
    also: ['greece'],
    note: 'Thoughts about love.'
    },
];

