const SUBJECTS = {
  paleontology:  'Paleontology',
  antiquity: 'Antiquity'
};

const RATINGS = { 4: 'Loved', 3: 'Liked', 2: 'Ok', 1: 'Didn\'t like' };
const KINDS = { book: 'Book', film: 'Film', music: 'Music', podcast: 'Podcast', play: 'Play' };

const ITEMS = [
  {
    id: 'prehistoricplanet',
    title: 'Prehistoric Planet',
    creator: 'Jon Favreau',
    year: 2022,
    yearEnd: 2025,
    kind: 'film',
    status: 'inprogress',
    rating: null,
    subject: 'paleontology',
    genre: 'Documentary',
    also: ['deeptime'],
    note: 'Many things are not based on strict facts but help imagine how life was really then.'
    },
  {
    id: 'iliad',
    title: 'Iliad',
    creator: 'Homer',
    year: -700,
    yearEnd: -650,
    kind: 'book',
    status: 'finished',
    rating: 3,
    subject: 'antiquity',
    genre: 'Epic',
    also: ['greece'],
    note: 'Lots of repeating (it\'s made to be told, not be written), the theory about several authors seems to be correct.'
    },
  {
    id: 'odyssey',
    title: 'Odyssey',
    creator: 'Homer',
    year: -800,
    yearEnd: -700,
    kind: 'book',
    status: 'finished',
    rating: 2,
    subject: 'antiquity',
    genre: 'Epic',
    also: ['greece'],
    note: 'Many "adventures" that can be hard to imagine.'
    },
  {
    id: 'odyssey2026',
    title: 'Odyssey',
    creator: 'Nolan',
    year: 2026,
    kind: 'film',
    status: 'finished',
    rating: 4,
    subject: 'antiquity',
    genre: 'Action',
    also: ['greece'],
    note: 'Story about returning from it.'
    },
  {
    id: 'worksanddays',
    title: 'Works and days',
    creator: 'Hesiod',
    year: -700,
    kind: 'book',
    status: 'finished',
    rating: 1,
    subject: 'antiquity',
    genre: 'Poem',
    also: ['greece'],
    note: 'Lots of advices that are not practical today.'
    },
  {
    id: 'theogony',
    title: 'Theogony',
    creator: 'Hesiod',
    year: -700,
    kind: 'book',
    status: 'finished',
    rating: 1,
    subject: 'antiquity',
    genre: 'Poem',
    also: ['greece'],
    note: 'Once again Greek myths.'
    },
  {
    id: 'aethiopica',
    title: 'Aethiopica',
    creator: 'Heliodorus of Emesa',
    year: -370,
    kind: 'book',
    status: 'finished',
    rating: 3,
    subject: 'antiquity',
    genre: 'Novel',
    also: ['greece'],
    note: 'Dramatic story about very beautiful people who are very kind, and very noble, and very lucky.'
    },
  {
    id: 'oresteia',
    title: 'The Oresteia',
    creator: 'Aeschylus',
    year: -550,
    kind: 'play',
    status: 'finished',
    rating: 4,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: 'Grand tragedy.'
    },
  {
    id: 'prometheusbound',
    title: 'Prometheus Bound',
    creator: 'Aeschylus',
    year: -424,
    kind: 'play',
    status: 'finished',
    rating: 2,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: 'Too pretentious.'
    },
  {
    id: 'oedipusrex',
    title: 'Oedipus Rex',
    creator: 'Sophocles',
    year: -429,
    kind: 'play',
    status: 'finished',
    rating: 3,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: 'Very dramatic and intense.'
    },
  {
    id: 'antigone',
    title: 'Antigone',
    creator: 'Sophocles',
    year: -441,
    kind: 'play',
    status: 'notstarted',
    rating: null,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: ''
    },
  {
    id: 'electrasophocles',
    title: 'Electra',
    creator: 'Sophocles',
    year: -420,
    kind: 'play',
    status: 'notstarted',
    rating: null,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: ''
    },
  {
    id: 'bacchae',
    title: 'The Bacchae',
    creator: 'Euripides',
    year: -405,
    kind: 'play',
    status: 'finished',
    rating: 4,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: 'Madness is so intense.'
    },
  {
    id: 'medea',
    title: 'Medea',
    creator: 'Euripides',
    year: -431,
    kind: 'play',
    status: 'finished',
    rating: 2,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: ''
    },
  {
    id: 'alcestis',
    title: 'Alcestis',
    creator: 'Euripides',
    year: -438,
    kind: 'play',
    status: 'finished',
    rating: 1,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: ''
    },
  {
    id: 'hippolytus',
    title: 'Hippolytus',
    creator: 'Euripides',
    year: -428,
    kind: 'play',
    status: 'notstarted',
    rating: null,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: ''
    },
  {
    id: 'electraeuripides',
    title: 'Electra',
    creator: 'Euripides',
    year: -413,
    kind: 'play',
    status: 'notstarted',
    rating: null,
    subject: 'antiquity',
    genre: 'Tragedy',
    also: ['greece'],
    note: ''
    },
  {
    id: 'lysistrata',
    title: 'Lysistrata',
    creator: 'Aristophanes',
    year: -411,
    kind: 'play',
    status: 'finished',
    rating: 2,
    subject: 'antiquity',
    genre: 'Comedy',
    also: ['greece'],
    note: 'Humour comes from women\'s powerless position in society.'
    },
  {
    id: 'frogs',
    title: 'The Frogs',
    creator: 'Aristophanes',
    year: -405,
    kind: 'play',
    status: 'finished',
    rating: 1,
    subject: 'antiquity',
    genre: 'Comedy',
    also: ['greece'],
    note: 'Comedy about who\'s better poet, pretty niche.'
    },
  {
    id: 'clouds',
    title: 'The Clouds',
    creator: 'Aristophanes',
    year: -423,
    kind: 'play',
    status: 'finished',
    rating: 1,
    subject: 'antiquity',
    genre: 'Comedy',
    also: ['greece'],
    note: 'Comedy about philosophers, very niche.'
    },
  {
    id: 'symposium',
    title: 'The Symposium',
    creator: 'Plato',
    year: -375,
    kind: 'book',
    status: 'finished',
    rating: 4,
    subject: 'antiquity',
    genre: 'Dialogue',
    also: ['greece'],
    note: 'Thoughts about love.'
    },
  {
    id: 'batrachomyomachia',
    title: 'Batrachomyomachia',
    creator: '-',
    year: -300,
    yearEnd: -200,
    kind: 'book',
    status: 'finished',
    rating: 3,
    subject: 'antiquity',
    genre: 'Poem',
    also: ['greece'],
    note: 'Parody of the Iliad.'
    },
  {
    id: 'callinuspoems',
    title: 'Poems',
    creator: 'Callinus',
    year: -650,
    kind: 'book',
    status: 'finished',
    rating: 1,
    subject: 'antiquity',
    genre: 'Poem',
    also: ['greece'],
    parts: [
        { title: 'Из воинственных элегий', status: 'finished', rating: 1 }
    ]
    },
  {
    id: 'tyrtaeuspoems',
    title: 'Poems',
    creator: 'Tyrtaeus',
    year: -700,
    yearEnd: -600,
    kind: 'book',
    status: 'finished',
    rating: 1,
    subject: 'antiquity',
    genre: 'Poem',
    also: ['greece'],
    parts: [
        { title: 'Благозаконие', status: 'finished', rating: 1 },
        { title: 'Война с Мессенией', status: 'finished', rating: 1 }
    ]
    },
  {
    id: 'mimnermuspoems',
    title: 'Poems',
    creator: 'Mimnermus',
    year: -550,
    yearEnd: -500,
    kind: 'book',
    status: 'finished',
    rating: 1,
    subject: 'antiquity',
    genre: 'Poem',
    also: ['greece'],
    parts: [
        { title: 'Без золотой Афродиты', status: 'finished', rating: 1 }
        ]
    },
  {
    id: 'solonpoems',
    title: 'Poems',
    creator: 'Solon',
    year: -500,
    kind: 'book',
    status: 'finished',
    rating: 2,
    subject: 'antiquity',
    genre: 'Poem',
    also: ['greece'],
    parts: [
        { title: 'Народ созвал я', status: 'finished', rating: 2 },
        { title: 'Из элегии Саламин', status: 'finished', rating: 1 }
        ]
    },
  {
    id: 'theognispoems',
    color: 'greece',
    title: 'Poems',
    creator: 'Theognis',
    creatorNative: 'Феогнид',
    year: -500,
    country: 'greece',
    kind: 'book',
    status: 'finished',
    rating: 1,
    subject: 'antiquity',
    genre: 'Poem',
    also: ['greece'],
    parts: [
        { title: 'С умыслом добрым тебя обучу я тому', status: 'finished', rating: 1 },
        { title: 'К низким людям, о Кирн, никогда не иди за советом', status: 'finished', rating: 1 },
        { title: 'Что мне в любви на словах', status: 'finished', rating: 1 },
        { title: 'Если тебя человек восхваляет', status: 'finished', rating: 1 },
        { title: 'Низкому сделав добро', status: 'finished', rating: 1 },
        { title: 'Нет в богатстве предела', status: 'finished', rating: 1 }
        ]
    },
  {
    id: 'archilochuspoems',
    color: 'greece',
    title: 'Poems',
    creator: 'Archilochus',
    year: -650,
    country: 'greece',
    kind: 'book',
    status: 'finished',
    rating: 2,
    subject: 'antiquity',
    genre: 'Poem',
    also: ['greece'],
    parts: [
        { title: 'Предоставь все божьей воле', status: 'finished', rating: 1 },
        { title: 'Жизнеотношение', status: 'finished', rating: 1 },
        { title: 'Можно ждать чего угодно', status: 'finished', rating: 1 },
        { title: 'Мне не мил стратег высокий', status: 'finished', rating: 2 },
        { title: 'Любовь. Необула', status: 'finished', rating: 1 },
        { title: 'Друзья и враги', status: 'finished', rating: 1 }
        ]
    },
  {
    id: 'hipponaxpoems',
    color: 'greece',
    title: 'Poems',
    creator: 'Hipponax',
    year: -550,
    country: 'greece',
    kind: 'book',
    status: 'finished',
    rating: 2,
    subject: 'antiquity',
    genre: 'Poem',
    also: ['greece'],
    parts: [
        { title: 'Гермес Килленский', status: 'finished', rating: 1 },
        { title: 'Ты не дал мне хламиды шерстяной, теплой', status: 'finished', rating: 2 },
        { title: 'Богатства бог, чье имя Плутос', status: 'finished', rating: 1 },
        { title: 'Я злу отдам усталую от мук душу', status: 'finished', rating: 2 }
        ]
    },
  {
    id: 'semonidesamorgospoems',
    color: 'greece',
    title: 'Poems',
    creator: 'Semonides of Amorgos',
    year: -650,
    country: 'greece',
    kind: 'book',
    status: 'finished',
    rating: 1,
    subject: 'antiquity',
    genre: 'Poem',
    also: ['greece'],
    parts: [
        { title: 'Различно женщин нрав сложил вначале Зевс', status: 'finished', rating: 1 }
        ]
    },
  {
    id: 'alcaeuspoems',
    color: 'greece',
    title: 'Poems',
    creator: 'Alcaeus',
    year: -620,
    yearEnd: -580,
    country: 'greece',
    kind: 'book',
    status: 'finished',
    rating: 3,
    subject: 'antiquity',
    genre: 'Poem',
    also: ['greece'],
    parts: [
        { title: 'Весна', status: 'finished', rating: 3 },
        { title: 'Гимн реке Гебру', status: 'finished', rating: 3 },
        { title: 'Что из кувшина черпать большим ковшом', status: 'finished', rating: 1 },
        { title: 'Буря не унимается', status: 'finished', rating: 1 },
        { title: 'Новый вал', status: 'finished', rating: 2 },
        { title: 'Алкей в святилище Геры', status: 'finished', rating: 2 },
        { title: 'Послание Питтаку', status: 'finished', rating: 1 },
        { title: 'Другу меланину', status: 'finished', rating: 1 },
        { title: 'К Сапфо', status: 'finished', rating: 2 },
        ]
    },
  {
    id: 'sapphopoems',
    color: 'greece',
    title: 'Poems',
    creator: 'Sappho',
    year: -630,
    yearEnd: -570,
    country: 'greece',
    kind: 'book',
    status: 'finished',
    rating: 3,
    subject: 'antiquity',
    genre: 'Poem',
    also: ['greece'],
    parts: [
        { title: 'Близ луны прекрасной', status: 'finished', rating: 1 },
        { title: 'Гимн Афродите', status: 'finished', rating: 1 },
        { title: 'Богу равным кажется мне по счастью', status: 'finished', rating: 1 },
        { title: 'Пещера нимф', status: 'finished', rating: 1 },
        { title: 'К брату Хараксу', status: 'finished', rating: 2 },
        { title: 'К Анактории', status: 'finished', rating: 2 },
        { title: 'Я к тебе взываю, Гонгила', status: 'finished', rating: 1 },
        { title: 'Мнится, легче разлуки смерть', status: 'finished', rating: 1 }
        ]
    },
  {
    id: 'anacreonpoems',
    color: 'greece',
    title: 'Poems',
    creator: 'Anacreon',
    year: -573,
    yearEnd: -485,
    country: 'greece',
    kind: 'book',
    status: 'finished',
    rating: 2,
    subject: 'antiquity',
    genre: 'Poem',
    also: ['greece'],
    parts: [
        { title: 'Артемиде', status: 'finished', rating: 1 },
        { title: 'Дионису', status: 'finished', rating: 1 },
        { title: 'Бросил шар свой пурпуровый', status: 'finished', rating: 2 },
        { title: 'Бросился я в ночь со скалы', status: 'finished', rating: 2 },
        { title: 'Поредели, побелели', status: 'finished', rating: 2 },
        { title: 'Кобылица молодая', status: 'finished', rating: 2 }
        ]
    },
];

